# Generated by Django 4.2.3 on 2023-08-14 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AreaName', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=120)),
                ('PublicTransportation', models.CharField(max_length=120)),
                ('Country', models.CharField(max_length=50)),
                ('Introduction', models.TextField()),
                ('Picture', models.ImageField(upload_to='Settlement/')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=80)),
                ('Body', models.TextField()),
                ('Picture', models.ImageField(upload_to='Settlement/Comment/')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SouthEastAsiaCommunityAtTaiwan.settlement')),
            ],
        ),
    ]
