# Generated by Django 4.2.3 on 2023-10-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SouthEastAsiaCommunityAtTaiwan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='Picture',
        ),
    ]
