# Generated by Django 4.2.3 on 2023-10-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SouthEastAsiaCommunityAtTaiwan', '0002_remove_reply_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
