# Generated by Django 4.2 on 2023-08-22 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_comment_photo_alter_restaurants_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='Rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
