# Generated by Django 4.2 on 2023-08-22 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_restaurants_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='Introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='People',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
