# Generated by Django 4.2 on 2023-08-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_pk',
        ),
    ]
