# Generated by Django 4.2 on 2023-08-23 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0009_rename_user_comment_user_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Photo',
        ),
        migrations.AlterField(
            model_name='comment',
            name='Rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
