# Generated by Django 4.2.3 on 2023-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_User', '0002_customuser_user_name_customuser_cell_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
